import Head from 'next/head'
import Image from 'next/image'
import { HiMenu } from 'react-icons/hi'
import { FiChevronDown } from 'react-icons/fi'
import { AiOutlineTwitter, AiOutlineGithub } from 'react-icons/ai'

import logo from '../public/imgs/logo-bookmark.svg'
import logoWhite from '../public/imgs/logo-bookmark-white.png'
import heroImg from '../public/imgs/hero-bg.png'
import featureImg1 from '../public/imgs/illustration-features-tab-1.png'
import featureImg2 from '../public/imgs/illustration-features-tab-2.png'
import featureImg3 from '../public/imgs/illustration-features-tab-3.png'
import logoChrome from '../public/imgs/logo-chrome.svg'
import logoFirefox from '../public/imgs/logo-firefox.svg'
import logoOpera from '../public/imgs/logo-opera.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS TypeScript TailwindCSS Stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header>
        <nav className="container flex items-center py-4 mt-4 sm:mt-12">
          <div className="py-1">
            <Image src={logo} alt="logo" />
          </div>
          <ul className="hidden sm:flex flex-1 justify-end items-center gap-12 text-custom-blue uppercase text-xs">
            <li className="cursor-pointer hover:text-custom-purple">
              features
            </li>
            <li className="cursor-pointer hover:text-custom-purple">pricing</li>
            <li className="cursor-pointer hover:text-custom-purple">contact</li>
            <form action="/api/checkout_sessions" method="POST">
              <button
                type="submit"
                className="bg-custom-red text-white rounded-md px-7 py-3 uppercase"
              >
                buy now
              </button>
            </form>
          </ul>
          <div className="flex sm:hidden flex-1 justify-end">
            <HiMenu className="text-2xl cursor-pointer" />
          </div>
        </nav>
      </header>

      {/* hero section */}
      <section className="relative">
        <div className="container flex flex-col-reverse lg:flex-row iterms:center gap-12 mt-14 lg:mt-28">
          {/* content */}
          <div className="flex flex-1 flex-col items-center lg:items-start">
            <h2 className="text-custom-blue text-3xl md:text-4 lg:text-5xl text-center lg:text-left mb-6">
              A simple bookmark manager
            </h2>
            <p className="text-custom-grey text-lg text-center lg:text-left mb-6">
              Placeholder vaporware with a clean design and a minimal interface
              to play around with TailwindCSS and it&apos;s utility classes.
            </p>
            <div className="flex justify-center flex-wrap gap-6 mt-12">
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                Get it on Chrome
              </button>
              <button
                type="button"
                className="btn btn-white hover:bg-custom-purple hover:text-custom-white"
              >
                Get it on Firefox
              </button>
            </div>
          </div>
          {/* image */}
          <div className="flex justify-center flex-1 mb-10 md:mb-16 lg:mb-0 z-10">
            <Image
              src={heroImg}
              alt="hero image"
              className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
            />
          </div>
        </div>
        <div className="hidden md:block overflow-hidden bg-custom-purple rounded-l-full absolute h-80 w-2/4 top-32 right-0 lg:-right-36"></div>
      </section>

      {/* features */}
      <section className="bg-custom-white py-20 mt-20 lg:mt-60">
        {/* heading */}
        <div className="sm:w-3/4 lg:w-5/12 mx-auto px-2">
          <h1 className="text-3xl text-center text-custom-blue">Features</h1>
          <p className="text-center text-custom-grey mt-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores
            iste voluptatibus corporis deleniti eligendi ratione dolores tenetur
            animi velit maxime.
          </p>
        </div>
        {/* feature 1 */}
        <div className="relative mt-20 lg:mt-24">
          {/* image */}
          <div className="container flex flex-col lg:flex-row items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={featureImg1}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">
                Bookmark in one click
              </h1>
              <p className="text-custom-grey mt-4 mb-12 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                quaerat suscipit eius maiores tempora? Laudantium at recusandae
                cumque modi qui.
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-r-full absolute h-60 w-2/4 top-32 right-0 -left-36" />
          </div>
        </div>
        {/* feature 2 */}
        <div className="relative mt-20 lg:mt-52">
          {/* image */}
          <div className="container flex flex-col lg:flex-row-reverse items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={featureImg3}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">Intelligent search</h1>
              <p className="text-custom-grey mt-4 mb-12 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum
                blanditiis possimus autem officiis et perspiciatis illo?
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-l-full absolute h-60 w-2/4 top-32 -right-36" />
          </div>
        </div>
        {/* feature 3 */}
        <div className="relative mt-20 lg:mt-24">
          {/* image */}
          <div className="container flex flex-col lg:flex-row items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={featureImg2}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">
                Share your bookmarks
              </h1>
              <p className="text-custom-grey mt-4 mb-12 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam
                fugit ut natus sint perspiciatis earum, excepturi, ducimus
                repellat cumque pariatur accusantium architecto.
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-r-full absolute h-60 w-2/4 top-32 right-0 -left-36" />
          </div>
        </div>
      </section>

      {/* download */}
      <section className="py-20 mt-20">
        {/* heading */}
        <div className="sm:w-3/4 lg:w-5/12 mx-auto px-2">
          <h1 className="text-3xl text-center text-custom-blue">
            Download the extension
          </h1>
          <p className="text-center text-custom-grey mt-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam,
            debitis.
          </p>
        </div>
        {/* cards */}
        <div className="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-16 max-w-screen-lg mt-16">
          {/* card 1 */}
          <div className="flex flex-col rounded-md shadow-md">
            <div className="p-6 flex flex-col items-center">
              <Image src={logoChrome} alt="chrome logo" />
              <h3 className="mt-5 text-custom-blue text-lg">Add to Chrome</h3>
              <p className="mb-2 text-custom-grey font-light">
                Minimum version 62
              </p>
            </div>
            <hr className="border-b border-custom-white" />
            <div className="flex p-6">
              <button className="flex-1 btn btn-purple hover:bg-custom-white hover:text-black">
                Install
              </button>
            </div>
          </div>
          {/* card 2 */}
          <div className="flex flex-col rounded-md shadow-md">
            <div className="p-6 flex flex-col items-center">
              <Image src={logoFirefox} alt="chrome logo" />
              <h3 className="mt-5 text-custom-blue text-lg">Add to Firefox</h3>
              <p className="mb-2 text-custom-grey font-light">
                Minimum version 62
              </p>
            </div>
            <hr className="border-b border-custom-white" />
            <div className="flex p-6">
              <button className="flex-1 btn btn-purple hover:bg-custom-white hover:text-black">
                Install
              </button>
            </div>
          </div>
          {/* card 3 */}
          <div className="flex flex-col rounded-md shadow-md">
            <div className="p-6 flex flex-col items-center">
              <Image src={logoOpera} alt="chrome logo" />
              <h3 className="mt-5 text-custom-blue text-lg">Add to Opera</h3>
              <p className="mb-2 text-custom-grey font-light">
                Minimum version 62
              </p>
            </div>
            <hr className="border-b border-custom-white" />
            <div className="flex p-6">
              <button className="flex-1 btn btn-purple hover:bg-custom-white hover:text-black">
                Install
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="bg-custom-white py-20">
        <div className="container">
          {/* heading */}
          <div className="sm:w-3/4 lg:w-2/4 mx-auto px-2">
            <h1 className="text-3xl text-center text-custom-blue">
              Frequently asked questions
            </h1>
            <p className="text-center text-custom-grey mt-4">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
              adipisci deserunt culpa placeat ducimus expedita tempore, pariatur
              quam amet debitis!
            </p>
          </div>
          {/* FAQ items */}
          <div className="flex flex-col sm:w-3/4 lg:w-2/4 mt-12 mx-auto">
            <div className="flex items-center border-b py-4">
              <span className="flex-1">What is a bookmark?</span>
              <FiChevronDown className="text-xl text-custom-purple" />
            </div>
            <div className="flex items-center border-b py-4">
              <span className="flex-1">How can I request a new browser?</span>
              <FiChevronDown className="text-xl text-custom-purple" />
            </div>
            <div className="flex items-center border-b py-4">
              <span className="flex-1">Is there a mobile app?</span>
              <FiChevronDown className="text-xl text-custom-purple" />
            </div>
            <div className="flex items-center border-b py-4">
              <span className="flex-1">
                What about other Chromium browsers?
              </span>
              <FiChevronDown className="text-xl text-custom-purple" />
            </div>
            <button className=" mt-12 flex self-center btn btn-purple hover:bg-custom-white hover:text-black">
              More info
            </button>
          </div>
        </div>
      </section>

      {/* contact */}
      <section className="bg-custom-purple text-white py-20">
        <div className="container">
          <div className="sm:w-3/4 lg:w-2/4 mx-auto">
            <p className="font-light uppercase text-center mb-8">
              35,000+ already joined
            </p>
            <h1 className="text-3xl text-center">
              Hear about product updates first
            </h1>
            <div className="flex flex-col sm:flex-row gap-6 mt-8">
              <input
                type="text"
                placeholder="Enter your email address"
                className="focus:outline-none flex-1 px-4 py-3 rounded-md text-black"
              />
              <button
                type="button"
                className="btn bg-custom-red hover:bg-custom-white hover:text-black"
              >
                Subscribe
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* footer */}
      <footer className="bg-custom-blue py-8">
        <div className="container flex flex-col md:flex-row items-center">
          <div className="flex flex-1 flex-wrap items-center justify-center md:justify-start gap-12">
            <Image src={logoWhite} alt="logo" />
            <ul className="flex text-white uppercase gap-12 text-xs">
              <li className="cursor-pointer">features</li>
              <li className="cursor-pointer">pricing</li>
              <li className="cursor-pointer">contact</li>
            </ul>
          </div>
          <div className="flex gap-10 mt-12 md:mt-0 text-2xl text-white">
            <AiOutlineTwitter />
            <AiOutlineGithub />
          </div>
        </div>
      </footer>
    </>
  )
}
