import Head from 'next/head'
import Image from 'next/image'
import logo from '../public/imgs/logo-bookmark.svg'
import HeroImg from '../public/imgs/hero-bg.png'
import FeatureImg1 from '../public/imgs/illustration-features-tab-1.png'
import FeatureImg2 from '../public/imgs/illustration-features-tab-2.png'
import FeatureImg3 from '../public/imgs/illustration-features-tab-3.png'
import { HiMenu } from 'react-icons/hi'

export default function Home() {
  return (
    <div className="font-Poppins overflow-hidden">
      <Head>
        <title>NextJS TypeScript TailwindCSS Stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header>
        <nav className="container flex items-center py-4 mt-4 sm:mt-12">
          <div className="py-1">
            <Image src={logo} alt="logo" />
          </div>
          <ul className="hidden sm:flex flex-1 justify-end items-center gap-12 text-custom-blue uppercase text-xs">
            <li className="cursor-pointer">features</li>
            <li className="cursor-pointer">pricing</li>
            <li className="cursor-pointer">contact</li>
            <button
              type="button"
              className="bg-custom-red text-white rounded-md px-7 py-3 uppercase"
            >
              login
            </button>
          </ul>
          <div className="flex sm:hidden flex-1 justify-end">
            <HiMenu className="text-2xl cursor-pointer" />
          </div>
        </nav>
      </header>

      {/* hero section */}
      <section className="relative">
        <div className="container flex flex-col-reverse lg:flex-row iterms:center gap-12 mt-14 lg:mt-28">
          {/* content */}
          <div className="flex flex-1 flex-col items-center lg:items-start">
            <h2 className="text-custom-blue text-3xl md:text-4 lg:text-5xl text-center lg:text-left mb-6">
              A simple bookmark manager
            </h2>
            <p className="text-custom-grey text-lg text-center lg:text-left mb-6">
              Placeholder vaporware with a clean design and a minimal interface
              to play around with TailwindCSS and it&apos;s utility classes.
            </p>
            <div className="flex justify-center flex-wrap gap-6">
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                Get it on Chrome
              </button>
              <button
                type="button"
                className="btn btn-white hover:bg-custom-purple hover:text-custom-white"
              >
                Get it on Firefox
              </button>
            </div>
          </div>
          {/* image */}
          <div className="flex justify-center flex-1 mb-10 md:mb-16 lg:mb-0 z-10">
            <Image
              src={HeroImg}
              alt="hero image"
              className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
            />
          </div>
        </div>
        <div className="hidden md:block overflow-hidden bg-custom-purple rounded-l-full absolute h-80 w-2/4 top-32 right-0 lg:-right-36"></div>
      </section>

      {/* features */}
      <section className="bg-custom-white py-20 mt-20 lg:mt-60">
        {/* heading */}
        <div className="sm:w-3/4 lg:w-5/12 mx-auto px-2">
          <h1 className="text-3xl text-center text-custom-blue">Features</h1>
          <p className="text-center text-custom-grey mt-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores
            iste voluptatibus corporis deleniti eligendi ratione dolores tenetur
            animi velit maxime.
          </p>
        </div>
        {/* feature 1 */}
        <div className="relative mt-20 lg:mt-24">
          {/* image */}
          <div className="container flex flex-col lg:flex-row items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={FeatureImg1}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">
                Bookmark in one click
              </h1>
              <p className="text-custom-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa
                quaerat suscipit eius maiores tempora? Laudantium at recusandae
                cumque modi qui.
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-r-full absolute h-60 w-2/4 top-32 right-0 -left-36" />
          </div>
        </div>
        {/* feature 2 */}
        <div className="relative mt-20 lg:mt-52">
          {/* image */}
          <div className="container flex flex-col lg:flex-row-reverse items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={FeatureImg3}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">Intelligent search</h1>
              <p className="text-custom-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum
                blanditiis possimus autem officiis et perspiciatis illo?
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-l-full absolute h-60 w-2/4 top-32 -right-36" />
          </div>
        </div>
        {/* feature 3 */}
        <div className="relative mt-20 lg:mt-24">
          {/* image */}
          <div className="container flex flex-col lg:flex-row items-center justify-center gap-x-24">
            {/* image */}
            <div className="flex flex-1 justify-center z-10 mb-10 lg:mb-0">
              <Image
                src={FeatureImg2}
                alt="feature image"
                className="w-5/6 h-5/6 sm:w-3/4 sm:h-3/4 md:w-full md:h-full"
              />
            </div>
            {/* content */}
            <div className="flex flex-1 flex-col items-center lg:items-start">
              <h1 className="text-3xl text-custom-blue">
                Share your bookmarks
              </h1>
              <p className="text-custom-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam
                fugit ut natus sint perspiciatis earum, excepturi, ducimus
                repellat cumque pariatur accusantium architecto.
              </p>
              <button
                type="button"
                className="btn btn-purple hover:bg-custom-white hover:text-black"
              >
                More info
              </button>
            </div>
            <div className="hidden lg:block overflow-hidden bg-custom-purple rounded-r-full absolute h-60 w-2/4 top-32 right-0 -left-36" />
          </div>
        </div>
      </section>
    </div>
  )
}
