import Head from 'next/head'
import Image from 'next/image'
import logo from '../public/imgs/logo-bookmark.svg'
import { HiMenu } from 'react-icons/hi'

export default function Home() {
  return (
    <div className="font-Poppins">
      <Head>
        <title>NextJS TypeScript TailwindCSS Stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <header>
        <nav className="container flex items-center py-4 mt-4 sm:mt-12">
          <div className="py-1">
            <Image src={logo} alt="logo" />
          </div>
          <ul className="hidden sm:flex flex-1 justify-end items-center gap-12 text-custom-blue uppercase text-xs">
            <li className="cursor-pointer">features</li>
            <li className="cursor-pointer">pricing</li>
            <li className="cursor-pointer">contact</li>
            <button
              type="button"
              className="bg-custom-red text-white rounded-md px-7 py-3 uppercase"
            >
              login
            </button>
          </ul>
          <div className="flex sm:hidden flex-1 justify-end">
            <HiMenu className="text-2xl cursor-pointer" />
          </div>
        </nav>
      </header>
    </div>
  )
}
